name: CI/CD for ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Asegúrate de que esta región sea la correcta

      # Paso 3: Loguearse en Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Paso 4: Crear el repositorio de ECR si no existe
      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-name prueba-2 || aws ecr create-repository --repository-name prueba-2 --region us-east-2

      # Paso 5: Construir la imagen Docker
      - name: Build Docker image
        run: |
          IMAGE_URI=971422693729.dkr.ecr.us-east-2.amazonaws.com/prueba-2:latest
          docker build -t $IMAGE_URI .
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      # Paso 6: Push de la imagen Docker a Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push $IMAGE_URI

      # Paso 7: Crear el servicio si no existe
      - name: Create ECS service if not exists
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services --cluster prueba_2 --services api-service --query "services[0].serviceName" --output text)
          if [ "$SERVICE_EXISTS" == "None" ]; then
            echo "Creating ECS service api-service"
            aws ecs create-service \
              --cluster prueba_2 \
              --service-name api-service \
              --task-definition ecs-task-definition.json \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[subnet-xxxxxxxx],securityGroups=[sg-xxxxxxxx],assignPublicIp=ENABLED}"
          else
            echo "ECS service api-service already exists"
          fi

      # Paso 8: Desplegar la imagen en ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          service: api-service
          cluster: prueba_2
          wait-for-service-stability: true
